name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: cv-generator-447314
  REGION: europe-west1
  SERVICE_NAME: cv-generator-api
  REGISTRY: europe-west1-docker.pkg.dev
  SERVICE_ACCOUNT: backend-flask@cv-generator-447314.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "service_suffix=-prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "service_suffix=-dev" >> $GITHUB_OUTPUT
          fi

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create Artifact Registry Repository
        run: |
          if ! gcloud artifacts repositories describe cloud-run-images --location=$REGION 2>/dev/null; then
            echo "Creating Artifact Registry repository..."
            gcloud artifacts repositories create cloud-run-images \
              --repository-format=docker \
              --location=$REGION \
              --description="Docker repository for Cloud Run images"
          fi

      - name: Test Authentication
        run: |
          echo "Testing GCP Authentication..."
          gcloud auth list
          gcloud projects list
          echo "Testing Docker Access..."
          gcloud auth configure-docker $REGISTRY --quiet
          echo "Testing Cloud Run Access..."
          gcloud run services list --platform managed --region $REGION

      - name: Build and Push Container
        if: github.ref != 'refs/heads/main'
        run: |
          docker build -t $REGISTRY/$PROJECT_ID/cloud-run-images/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }} .
          docker push $REGISTRY/$PROJECT_ID/cloud-run-images/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }}

      - name: Get Dev Image Tag
        if: github.ref == 'refs/heads/main'
        id: get-dev-image
        run: |
          DEV_IMAGE=$(gcloud run services describe $SERVICE_NAME-dev --region $REGION --format 'value(spec.template.spec.containers[0].image)')
          echo "dev_image=$DEV_IMAGE" >> $GITHUB_OUTPUT

      - name: Promote Dev Image to Prod
        if: github.ref == 'refs/heads/main'
        run: |
          DEV_IMAGE=${{ steps.get-dev-image.outputs.dev_image }}
          SHA=$(echo $DEV_IMAGE | cut -d':' -f2)
          PROD_IMAGE=$REGISTRY/$PROJECT_ID/cloud-run-images/$SERVICE_NAME-prod:$SHA
          
          echo "Promoting dev image to prod:"
          echo "From: $DEV_IMAGE"
          echo "To: $PROD_IMAGE"
          
          # Pull l'image dev
          docker pull $DEV_IMAGE
          # Tag comme prod
          docker tag $DEV_IMAGE $PROD_IMAGE
          # Push l'image prod
          docker push $PROD_IMAGE

      - name: Deploy to Cloud Run
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            # Pour prod, utiliser l'image promue depuis dev
            SHA=$(echo ${{ steps.get-dev-image.outputs.dev_image }} | cut -d':' -f2)
            IMAGE=$REGISTRY/$PROJECT_ID/cloud-run-images/$SERVICE_NAME-prod:$SHA
          else
            # Pour dev, utiliser la nouvelle image construite
            IMAGE=$REGISTRY/$PROJECT_ID/cloud-run-images/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }}
          fi
          
          echo "Deploying image: $IMAGE"
          
          gcloud run deploy $SERVICE_NAME${{ steps.env.outputs.service_suffix }} \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ env.SERVICE_ACCOUNT }} \
            --set-env-vars="ENV=${{ steps.env.outputs.environment }},LANGSMITH_TRACING=true,LANGSMITH_ENDPOINT=https://api.smith.langchain.com,LANGSMITH_PROJECT=backend-dev" \
            --update-secrets="OPENAI_API_KEY=OPENAI_API_KEY:latest,LANGSMITH_API_KEY=LANGSMITH_API_KEY:latest"

      - name: Test Health Endpoint (Dev Only)
        if: github.ref != 'refs/heads/main'
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME${{ steps.env.outputs.service_suffix }} --region $REGION --format 'value(status.url)')
          echo "Service URL: $SERVICE_URL"
          
          # Attendre que le service soit prêt (max 60 secondes)
          for i in {1..12}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health")
            if [ "$response" = "200" ]; then
              echo "Health check passed!"
              exit 0
            fi
            echo "Waiting for service to be ready... (attempt $i/12)"
            sleep 5
          done
          
          echo "Health check failed after 60 seconds"
          exit 1

      - name: Test Deployment (Prod Only)
        if: github.ref == 'refs/heads/main'
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME${{ steps.env.outputs.service_suffix }} --region $REGION --format 'value(status.url)')
          echo "Service URL: $SERVICE_URL"
          curl -f -s "$SERVICE_URL" || echo "Service is deployed but might need initialization"