name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # déploiement en prod
      - develop  # déploiement en dev
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

env:
  PROJECT_ID: cv-generator-447314
  REGION: europe-west1
  SERVICE_NAME: cv-generator-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "service_suffix=-prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "service_suffix=-dev" >> $GITHUB_OUTPUT
          fi

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }} backend/
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME${{ steps.env.outputs.service_suffix }} \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME${{ steps.env.outputs.service_suffix }}:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="ENV=${{ steps.env.outputs.environment }}"