name: Test Endpoints

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

env:
  PROJECT_ID: cv-generator-447314

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Make test script executable
      run: chmod +x tests/test_endpoints.sh
      
    - name: Run endpoint tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: ./tests/test_endpoints.sh 