name: Test Endpoints

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > service-account.json

    - name: Make test script executable
      run: chmod +x tests/test_endpoints.sh
      
    - name: Run endpoint tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
      run: ./tests/test_endpoints.sh 